global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:5000']

  - job_name: 'ml'
    static_configs:
      - targets: ['ml:5000']

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow:8080']

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000'] 